require "prawn"

# Class containing the logic for generating pdf from the contract

class PdfGenerator
    def initialize(contract)
        @contract = contract
        @pdf = Prawn::Document.new(:info => contract.data)
    end

    def generate
        @pdf.repeat(:all) do
            @pdf.draw_text "Generated by ContractIO", :at => [10, 10]
        end
        @pdf.font_size = 24
        @pdf.text @contract.contract_type + " Agreement", :align => :center
        @pdf.move_down 20
        clause_counter = 1
        @pdf.font_size = 12
        @contract.clauses.each do |clause|
            current_clause = Clause.find(clause)
            current_text = clause_counter.to_s + ". "
            current_text += current_clause.text
            @pdf.text current_text
            clause_counter += 1
            @pdf.move_down 10
        end

        if @contract.contract_type == "Loan"
            generate_loan_bottom_template
        end
    end

    def render
        @pdf.render
    end

    def generate_loan_bottom_template
        @pdf.text "The Parties agree to the terms and conditions set forth above as demonstrated by their signatures as follows:"
        @pdf.move_down 10
        @pdf.text "<b>\"LENDER\"</b>", :inline_format => true
        @pdf.move_down 10
        @pdf.text "Signed:"
        @pdf.move_down 25
        @pdf.text "<b>\"Borrower\"</b>", :inline_format => true
        @pdf.move_down 10
        @pdf.text "signed:"
    end
  end
  